services:
  db:
    image: postgres:16-alpine
    ports:
      - "5412:5432"
    volumes:
      - jpgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: ["postgres", "-c", "log_statement=none"]

volumes:
  jpgdata: